import fs from "fs/promises"
import path, { dirname } from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const projectRoot = path.resolve(__dirname, "../")
const componentsDemoDir = path.join(projectRoot, "registry-components/examples")
const componentsDir = path.join(projectRoot, "components/library")
const outputFile = path.join(
    projectRoot,
    "registry-components/component-examples.ts"
)
const registryOutputFile = path.join(
    projectRoot,
    "registry-components/index.ts"
)

const sourceMapDemoOutputFile = path.join(
    projectRoot,
    "registry-components/component-demo-source-map.json"
)

const sourceMapOutputFile = path.join(
    projectRoot,
    "registry-components/component-source-map.json"
)

async function getAllTSXFiles(dir) {
    try {
        let entries = await fs.readdir(dir, { withFileTypes: true })
        let files = await Promise.all(
            entries.map((entry) => {
                const fullPath = path.join(dir, entry.name)
                if (entry.isDirectory()) {
                    return getAllTSXFiles(fullPath)
                } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
                    return [fullPath]
                } else {
                    return []
                }
            })
        )
        return files.flat()
    } catch (error) {
        console.error(`Error reading directory ${dir}:`, error)
        return []
    }
}

function parseComponentInfo(filePath) {
    const fileName = path.basename(filePath, ".tsx")
    const match = fileName.match(/^(.+?)(?:-(.+?))?-demo$/)

    if (match) {
        const baseName = match[1]
        const variant = match[2] || null
        return { baseName, variant, fullName: fileName }
    }

    return { baseName: fileName, variant: null, fullName: fileName }
}

function toImportPath(filePath) {
    const relativePath = path.relative(projectRoot, filePath).replace(/\\/g, "/")
    const importPath = relativePath.replace(/\.tsx$/, "")
    return `@/${importPath}`
}

async function readFileContent(filePath) {
    try {
        return await fs.readFile(filePath, 'utf-8')
    } catch (error) {
        console.error(`Error reading file ${filePath}:`, error)
        return null
    }
}
async function generateFiles() {
    console.log(`Looking for TSX files in: ${componentsDir}`)

    try {
        await fs.access(componentsDir)
        await fs.access(componentsDemoDir)
    } catch (error) {
        console.error(`Directory not found: ${componentsDir}`)
        process.exit(1)
    }

    const demoComponentFile = await getAllTSXFiles(componentsDemoDir)
    const ComponentFile = await getAllTSXFiles(componentsDir)

    if (ComponentFile.length === 0) {
        console.warn(`No TSX files found in ${componentsDir}`)
    } else {
        console.log(`Found ${ComponentFile.length} TSX files`)
    }

    const registryItems = []
    const componentSourceMap = {}
    const componentDemoSourceMap = {}

    // Process all components first
    for (const component of ComponentFile) {
        const importComponent = toImportPath(component)
        const fileContent = await readFileContent(component)

        if (fileContent) {
            componentSourceMap[importComponent] = fileContent
        }
    }

    // Then process demo components
    for (const demoComponent of demoComponentFile) {
        const { baseName, variant, fullName } = parseComponentInfo(demoComponent)
        const importPathForDemo = toImportPath(demoComponent)
        const fileContent = await readFileContent(demoComponent)

        // Find the matching component file
        const matchingComponentFile = ComponentFile.find((file) =>
            path.basename(file, '.tsx').includes(baseName)
        )

        // Use a default or the actual component path if found
        const componentImportPath = matchingComponentFile
            ? toImportPath(matchingComponentFile)
            : `@/components/library/${baseName}` // Fallback path

        // Add to registry items
        registryItems.push(`    {
        name: "${fullName}",
        baseComponent: "${baseName}",
        variant: ${variant ? `"${variant}"` : "null"},
        componentPath: "${componentImportPath}",
        componentDemoPath: "${importPathForDemo}",
        component: React.lazy(() => import("${importPathForDemo}"))
      }`)

        if (fileContent) {
            componentDemoSourceMap[importPathForDemo] = fileContent
        }
    }

    // Rest of the code remains the same...
    const componentExamplesResult = `// This file was automatically generated by component-utils.mjs
  import React from "react";
  
  export const componentExamples = {
    items: [
  ${registryItems.join(",\n")}
    ]
  };
  `

    const registryResult = `// This file was automatically generated by component-utils.mjs
  import { componentExamples } from "./component-examples"
  
  export const REGISTRY_COMPONENTS = {
    name: "alphabyte-labs",
    items: [...componentExamples.items],
  }
  `

    try {
        const outputDir = path.dirname(outputFile)
        await fs.mkdir(outputDir, { recursive: true })

        await fs.writeFile(outputFile, componentExamplesResult, "utf-8")
        console.log(`✅ Generated file: ${outputFile}`)
        await fs.writeFile(registryOutputFile, registryResult, "utf-8")
        console.log(`✅ Generated file: ${registryOutputFile}`)
        await fs.writeFile(sourceMapOutputFile, JSON.stringify(componentSourceMap, null, 2), "utf-8")
        console.log(`✅ Generated file: ${sourceMapOutputFile}`)
        await fs.writeFile(sourceMapDemoOutputFile, JSON.stringify(componentDemoSourceMap, null, 2), "utf-8")
        console.log(`✅ Generated file: ${sourceMapDemoOutputFile}`)
    } catch (error) {
        console.error(`Error writing files:`, error)
    }
}
generateFiles().catch((err) => {
    console.error("Error generating component files:", err)
    process.exit(1)
})
