// This file was automatically generated by block-utils.mjs
// @ts-nocheck
export const blockExamples = {
    name: "alphabyte-blocks",
    items: [
        {
            name: "about-1",
            target: "@/registry-blocks/view/about-1/page",
            components: ["@/registry-blocks/view/about-1/components/about"],
        },
        {
            name: "carousel-1",
            target: "@/registry-blocks/view/carousel-1/page",
            components: [
                "@/registry-blocks/view/carousel-1/components/carousel-container",
                "@/registry-blocks/view/carousel-1/components/carousel",
            ],
        },
        {
            name: "carousel-2",
            target: "@/registry-blocks/view/carousel-2/page",
            components: [
                "@/registry-blocks/view/carousel-2/components/carousel-container",
                "@/registry-blocks/view/carousel-2/components/carousel",
            ],
        },
        {
            name: "navbar-1",
            target: "@/registry-blocks/view/navbar-1/page",
            components: ["@/registry-blocks/view/navbar-1/components/navbar"],
        },
        {
            name: "new-collection-1",
            target: "@/registry-blocks/view/new-collection-1/page",
            components: [
                "@/registry-blocks/view/new-collection-1/components/new-collection",
            ],
        },
        {
            name: "service-1",
            target: "@/registry-blocks/view/service-1/page",
            components: ["@/registry-blocks/view/service-1/components/service"],
        },
        {
            name: "timeline-1",
            target: "@/registry-blocks/view/timeline-1/page",
            components: [
                "@/registry-blocks/view/timeline-1/components/timeline-container",
                "@/registry-blocks/view/timeline-1/components/timeline",
            ],
        },
    ],
}
