// This file was automatically generated by block-utils.mjs
import { blockExamples } from "./blocks-examples";

export const REGISTRY_BLOCKS = {
  name: "alphabyte-blocks",
  items: [...blockExamples.items],
};
