// This file was automatically generated by component-utils.mjs
// Contains raw component source code for direct access

export const COMPONENT_SOURCE_MAP = {
  "@/registry-components/examples/accordion-demo/accordion-demo": `import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/library/accordion"

const AccordionDemo = () => {
  return (
    <Accordion type="multiple" className="w-full max-w-2xl">
      <AccordionItem value="tech-1">
        <AccordionTrigger>MacOS</AccordionTrigger>
        <AccordionContent>
          macOS is Apple's desktop operating system that powers Mac computers.
          It features a sleek user interface, robust security features, and
          seamless integration with other Apple devices and services.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="tech-2">
        <AccordionTrigger>iOS</AccordionTrigger>
        <AccordionContent>
          iOS is Apple's mobile operating system for iPhone. It's known for its
          intuitive interface, app ecosystem, security, and consistent
          performance across devices.
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="tech-3">
        <AccordionTrigger>iPadOS</AccordionTrigger>
        <AccordionContent>
          iPadOS is a variant of iOS designed specifically for iPad, with
          features optimized for the larger display, including improved
          multitasking, Apple Pencil support, and desktop-class browsing.
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  )
}

export default AccordionDemo
`,
  "@/registry-components/examples/alert-dialog-demo/alert-dialog-demo": `import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/library/alert-dialog"
import { Button } from "@/components/library/button"

export default function AlertDialogDemo() {
  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button variant="outline">Open Dialog</Button>
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>Are you sure?</AlertDialogTitle>
          <AlertDialogDescription>
            This action cannot be undone. The data will be permanently deleted
            from the servers.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction>Continue</AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
`,
  "@/registry-components/examples/alert-dialog-demo/alert-dialog-destructive-demo": `import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/library/alert-dialog"
import { Button } from "@/components/library/button"

export default function AlertDialogDemo() {
  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button variant="destructive">Open Dialog</Button>
      </AlertDialogTrigger>
      <AlertDialogContent appearance="destructive">
        <AlertDialogHeader>
          <AlertDialogTitle>Are you sure?</AlertDialogTitle>
          <AlertDialogDescription>
            This action cannot be undone. The data will be permanently deleted
            from the servers.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction variant="destructive">Continue</AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
`,
  "@/registry-components/examples/alert-dialog-demo/alert-dialog-lg-demo": `import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/library/alert-dialog"
import { Button } from "@/components/library/button"

const AlertDialogLgDemo = () => {
  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button variant="outline">Large Dialog</Button>
      </AlertDialogTrigger>
      <AlertDialogContent size="lg">
        <AlertDialogHeader>
          <AlertDialogTitle>Large Dialog</AlertDialogTitle>
          <AlertDialogDescription>
            This is an example of a large dialog. It can be used to display
            larger content.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction>Continue</AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}

export default AlertDialogLgDemo
`,
  "@/registry-components/examples/alert-dialog-demo/alert-dialog-sm-demo": `import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/library/alert-dialog"
import { Button } from "@/components/library/button"

const AlertDialogSmDemo = () => {
  return (
    <div className="flex flex-col gap-4">
      <AlertDialog>
        <AlertDialogTrigger asChild>
          <Button variant="outline">Small Dialog</Button>
        </AlertDialogTrigger>
        <AlertDialogContent size="sm">
          <AlertDialogHeader>
            <AlertDialogTitle>Small Dialog</AlertDialogTitle>
            <AlertDialogDescription>
              This is an example of a small dialog.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction>Continue</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}

export default AlertDialogSmDemo
`,
  "@/registry-components/examples/badge-demo/badge-demo": `import { Badge } from "@/components/library/badge"

const BadgeDemo = () => {
  return <Badge>Badge</Badge>
}

export default BadgeDemo
`,
  "@/registry-components/examples/badge-demo/badge-destructive-demo": `import { Badge } from "@/components/library/badge"

const BadgeDestructiveDemo = () => {
  return <Badge variant="destructive">Destructive</Badge>
}

export default BadgeDestructiveDemo
`,
  "@/registry-components/examples/badge-demo/badge-icon-demo": `import { Lock } from "lucide-react"
import { Badge } from "@/components/library/badge"

const BadgeIconDemo = () => {
  return (
    <Badge variant="default" icon={<Lock size={12} />}>
      Secure
    </Badge>
  )
}

export default BadgeIconDemo
`,
  "@/registry-components/examples/badge-demo/badge-info-demo": `import { Badge } from "@/components/library/badge"

const BadgeInfoDemo = () => {
  return <Badge variant="info">Info</Badge>
}

export default BadgeInfoDemo
`,
  "@/registry-components/examples/badge-demo/badge-outline-demo": `import { Badge } from "@/components/library/badge"

const BadgeOutlineDemo = () => {
  return <Badge variant="outline">Outline</Badge>
}

export default BadgeOutlineDemo
`,
  "@/registry-components/examples/badge-demo/badge-removable-demo": `"use client"
import { Badge } from "@/components/library/badge"
import { useState } from "react"

const BadgeRemoveAbleDemo = () => {
  const [isVisible, setIsVisible] = useState(true)

  if (!isVisible) {
    return null
  }

  return (
    <Badge
      variant="outline"
      removable={true}
      onRemove={() => setIsVisible(false)}
    >
      Apple
    </Badge>
  )
}

export default BadgeRemoveAbleDemo
`,
  "@/registry-components/examples/badge-demo/badge-secondary-demo": `import { Badge } from "@/components/library/badge"

const BadgeSecondaryDemo = () => {
  return <Badge variant="secondary">Secondary</Badge>
}

export default BadgeSecondaryDemo
`,
  "@/registry-components/examples/badge-demo/badge-success-demo": `import { Badge } from "@/components/library/badge"

const BadgeSuccessDemo = () => {
  return <Badge variant="success">Success</Badge>
}

export default BadgeSuccessDemo
`,
  "@/registry-components/examples/badge-demo/badge-warning-demo": `import { Badge } from "@/components/library/badge"

const BadgeWarningDemo = () => {
  return <Badge variant="warning">Warning</Badge>
}

export default BadgeWarningDemo
`,
  "@/registry-components/examples/breadcrumb-demo/breadcrumb-custom-separator-demo": `import { LuStar } from "react-icons/lu"

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/library/breadcrumb"

const BreadcrumbCustomSeparator = () => {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="/">Home</BreadcrumbLink>
          {/* Here You can add any icon you want inside the BreadcrumbSeparator */}
          <BreadcrumbSeparator>/</BreadcrumbSeparator>
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbLink href="/about">About</BreadcrumbLink>
          <BreadcrumbSeparator>/</BreadcrumbSeparator>
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbLink href="/about/team">Team</BreadcrumbLink>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default BreadcrumbCustomSeparator
`,
  "@/registry-components/examples/breadcrumb-demo/breadcrumb-demo": `import { HiHome } from "react-icons/hi2"

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/library/breadcrumb"

const BreadcrumbDemo = () => {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="#">
            <HiHome className="h-4 w-4" />
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbLink href="#">Documents</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbPage>Current Page</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default BreadcrumbDemo
`,
  "@/registry-components/examples/breadcrumb-demo/breadcrumb-dropdown-demo": `import {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/library/breadcrumb"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/library/dropdown-menu"

const BreadcrumbDropdownMenu = () => {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="/">Home</BreadcrumbLink>
          <BreadcrumbSeparator />
        </BreadcrumbItem>
        <BreadcrumbItem>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <span className="cursor-pointer">
                <BreadcrumbEllipsis />
              </span>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>
                <BreadcrumbLink href="/products">Products</BreadcrumbLink>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <BreadcrumbLink href="/services">Services</BreadcrumbLink>
              </DropdownMenuItem>
              <DropdownMenuItem>
                <BreadcrumbLink href="/blog">Blog</BreadcrumbLink>
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <BreadcrumbSeparator />
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbLink href="/current">Current Page</BreadcrumbLink>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default BreadcrumbDropdownMenu
`,
  "@/registry-components/examples/breadcrumb-demo/breadcrumb-ellipsis-demo": `import { HiHome } from "react-icons/hi2"

import {
  Breadcrumb,
  BreadcrumbEllipsis,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/library/breadcrumb"

const BreadcrumbEllipsisDemo = () => {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="#">
            <HiHome className="h-4 w-4" />
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbEllipsis />
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbLink href="#">Projects</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbPage>Current Page</BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default BreadcrumbEllipsisDemo
`,
  "@/registry-components/examples/breadcrumb-demo/breadcrumb-icons-demo": `import { HiDocument, HiFolder, HiHome } from "react-icons/hi2"

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/library/breadcrumb"

const BreadcrumbIconsDemo = () => {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="#" className="flex items-center gap-1">
            <HiHome className="h-4 w-4" />
            <span>Home</span>
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbLink href="#" className="flex items-center gap-1">
            <HiFolder className="h-4 w-4" />
            <span>Projects</span>
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbLink href="#" className="flex items-center gap-1">
            <HiFolder className="h-4 w-4" />
            <span>Web Development</span>
          </BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        <BreadcrumbItem>
          <BreadcrumbPage className="flex items-center gap-1">
            <HiDocument className="h-4 w-4" />
            <span>Project Details</span>
          </BreadcrumbPage>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default BreadcrumbIconsDemo
`,
  "@/registry-components/examples/breadcrumb-demo/breadcrumb-responsive-demo": `import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/library/breadcrumb"

const BreadcrumbResponsiveDemo = () => {
  return (
    <Breadcrumb>
      <BreadcrumbList className="flex flex-wrap">
        <BreadcrumbItem>
          <BreadcrumbLink href="/">Home</BreadcrumbLink>
          <BreadcrumbSeparator />
        </BreadcrumbItem>
        <BreadcrumbItem className="hidden sm:flex">
          <BreadcrumbLink href="/category">Category</BreadcrumbLink>
          <BreadcrumbSeparator />
        </BreadcrumbItem>
        <BreadcrumbItem className="hidden md:flex">
          <BreadcrumbLink href="/category/subcategory">
            Subcategory
          </BreadcrumbLink>
          <BreadcrumbSeparator />
        </BreadcrumbItem>
        <BreadcrumbItem>
          <BreadcrumbLink href="/category/subcategory/item">
            Item
          </BreadcrumbLink>
        </BreadcrumbItem>
      </BreadcrumbList>
    </Breadcrumb>
  )
}

export default BreadcrumbResponsiveDemo
`,
  "@/registry-components/examples/button-demo/button-bounce-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonBounceAnimationDemo = () => {
  return <Button animation={"bounce"}>Bounce Animation button</Button>
}

export default ButtonBounceAnimationDemo
`,
  "@/registry-components/examples/button-demo/button-demo": `import { Button } from "@/components/library/button"

export default function ButtonDemo() {
  return <Button variant={"default"}>Getting Started</Button>
}
`,
  "@/registry-components/examples/button-demo/button-destructive-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonDestructiveDemo = () => {
  return <Button variant="destructive">Destructive button</Button>
}

export default ButtonDestructiveDemo
`,
  "@/registry-components/examples/button-demo/button-ghost-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonGhostDemo = () => {
  return <Button variant="ghost">Ghost button</Button>
}

export default ButtonGhostDemo
`,
  "@/registry-components/examples/button-demo/button-icon-demo": `import React from "react"
import { ChevronRightIcon } from "lucide-react"

import { Button } from "@/components/library/button"

const ButtonIconDemo = () => {
  return (
    <Button variant="outline">
      <ChevronRightIcon className="w-6 h-6" />
    </Button>
  )
}

export default ButtonIconDemo
`,
  "@/registry-components/examples/button-demo/button-link-demo": `import React from "react"
import { Link } from "@/i18n/routing"

import { Button } from "@/components/library/button"

const ButtonLinkDemo = () => {
  return (
    <Button variant="link" asChild>
      <Link href={"/href"}>Link button</Link>
    </Button>
  )
}

export default ButtonLinkDemo
`,
  "@/registry-components/examples/button-demo/button-loading-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonLoadingDemo = () => {
  return <Button isLoading>Loading...</Button>
}

export default ButtonLoadingDemo
`,
  "@/registry-components/examples/button-demo/button-neural-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonNeuralDemo = () => {
  return <Button variant="neural">Neural button</Button>
}

export default ButtonNeuralDemo
`,
  "@/registry-components/examples/button-demo/button-outline-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonOutlineDemo = () => {
  return <Button variant={"outline"}>Outline button</Button>
}

export default ButtonOutlineDemo
`,
  "@/registry-components/examples/button-demo/button-primary-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonPrimaryDemo = () => {
  return <Button variant="default">Primary button</Button>
}

export default ButtonPrimaryDemo
`,
  "@/registry-components/examples/button-demo/button-pulse-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonPulseAnimationDemo = () => {
  return <Button animation={"pulse"}>Pulse Animation button</Button>
}

export default ButtonPulseAnimationDemo
`,
  "@/registry-components/examples/button-demo/button-secondary-demo": `import React from "react"

import { Button } from "@/components/library/button"

const ButtonSecondaryDemo = () => {
  return <Button variant="secondary">Secondary button</Button>
}

export default ButtonSecondaryDemo
`,
  "@/registry-components/examples/calendar-demo": `"use client"

import * as React from "react"

import { Calendar } from "@/components/library/calendar"

export default function CalendarDemo() {
  const [date, setDate] = React.useState<Date | undefined>(new Date())

  return <Calendar mode="single" selected={date} onSelect={setDate} />
}
`,
  "@/registry-components/examples/code-block-demo": `import { cn } from "@/lib/utils"
import Pre from "@/components/pre"

const CodeBlockDemo = ({ className }: { className: string }) => {
  const ExampleCode = \`function MyComponent(props) {
   return (
      <div>
         <h1>Hello, {props.name}!</h1>
         <p>This is an example React component.</p>
      </div>
   )};\`
  return (
    <Pre
      className={cn("", className)}
      highlightLines={[4]}
      showLineNumbers={true}
    >
      {ExampleCode}
    </Pre>
  )
}

export default CodeBlockDemo
`,
  "@/registry-components/examples/collapsible-demo/collapsible-demo": `"use client"

import * as React from "react"
import { ChevronsUpDown } from "lucide-react"

import { Button } from "@/components/library/button"
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/library/collapsible"

export default function CollapsibleDemo() {
  const [isOpen, setIsOpen] = React.useState(false)
  return (
    <Collapsible
      open={isOpen}
      onOpenChange={setIsOpen}
      className="w-[350px] space-y-2"
    >
      <div className="flex items-center justify-between space-x-4 px-4">
        <h4 className="text-sm font-semibold">
          @peduarte starred 3 repositories
        </h4>
        <CollapsibleTrigger asChild>
          <Button variant="ghost" size="sm">
            <ChevronsUpDown className="h-4 w-4" />
            <span className="sr-only">Toggle</span>
          </Button>
        </CollapsibleTrigger>
      </div>
      <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
        @radix-ui/primitives
      </div>
      <CollapsibleContent className="space-y-2">
        <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
          @radix-ui/colors
        </div>
        <div className="rounded-md border px-4 py-2 font-mono text-sm shadow-sm">
          @stitches/react
        </div>
      </CollapsibleContent>
    </Collapsible>
  )
}
`,
  "@/registry-components/examples/date-picker-demo/date-picker-demo": `"use client"

import * as React from "react"
import { format } from "date-fns"
import { CalendarIcon } from "lucide-react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/library/button"
import { Calendar } from "@/components/library/calendar"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/library/popover"

export default function DatePickerDemo() {
  const [date, setDate] = React.useState<Date>()

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant={"outline"}
          className={cn(
            "w-[240px] justify-start text-left font-normal",
            !date && "text-muted-foreground"
          )}
        >
          <CalendarIcon strokeWidth={2.1} absoluteStrokeWidth />
          {date ? (
            format(date, "PPP")
          ) : (
            <span className="font-normal">Pick a date</span>
          )}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <Calendar
          mode="single"
          selected={date}
          onSelect={setDate}
          initialFocus
        />
      </PopoverContent>
    </Popover>
  )
}
`,
  "@/registry-components/examples/date-picker-demo/date-picker-range-demo": `"use client"

import * as React from "react"
import { addDays, format } from "date-fns"
import { CalendarIcon } from "lucide-react"
import type { DateRange } from "react-day-picker"

import { cn } from "@/lib/utils"
import { Button } from "@/components/library/button"
import { Calendar } from "@/components/library/calendar"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/library/popover"

export default function DatePickerRangeDemo({
  className,
}: React.HTMLAttributes<HTMLDivElement>) {
  const [date, setDate] = React.useState<DateRange | undefined>({
    from: new Date(),
    to: addDays(new Date(), 7),
  })

  return (
    <div className={cn("grid gap-2", className)}>
      <Popover>
        <PopoverTrigger asChild>
          <Button
            id="date"
            variant={"outline"}
            className={cn(
              "w-full justify-start text-left font-normal",
              !date && "text-muted-foreground"
            )}
          >
            <CalendarIcon strokeWidth={2.1} className="mr-2 h-4 w-4" />
            {date?.from ? (
              date.to ? (
                <span className="font-normal">
                  {format(date.from, "LLL dd, y")} -{" "}
                  {format(date.to, "LLL dd, y")}
                </span>
              ) : (
                format(date.from, "LLL dd, y")
              )
            ) : (
              <span className="font-normal">Pick a date</span>
            )}
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-auto p-0" align="start">
          <Calendar
            initialFocus
            mode="range"
            defaultMonth={date?.from}
            selected={date}
            onSelect={setDate}
            numberOfMonths={2}
          />
        </PopoverContent>
      </Popover>
    </div>
  )
}
`,
  "@/registry-components/examples/diagram-demo/diagram-decision-tree-demo": `import React from "react"

import Mermaid from "@/components/library/mermaid"

const DiagramDecisionTreeDemo = () => {
  return (
    <Mermaid
      chart={\`graph TD;
    A[Start] --> B{Is it raining?};
    B -->|Yes| C[Take an umbrella];
    B -->|No| D[Enjoy the weather];
    C --> E[Go outside];
    D --> E;\`}
    />
  )
}

export default DiagramDecisionTreeDemo
`,
  "@/registry-components/examples/diagram-demo/diagram-demo": `import Mermaid from "@/components/library/mermaid"

const DiagramsDemo = () => {
  return (
    <Mermaid
      chart={\`graph TD;
    Start --> Task1;
    Task1 --> Task2;
    Task2 --> End;\`}
    />
  )
}

export default DiagramsDemo
`,
  "@/registry-components/examples/diagram-demo/diagram-entity-relationship-demo": `import Mermaid from "@/components/library/mermaid"

const DiagramsEntityRelationShipDemo = () => {
  return (
    <Mermaid
      chart={\`erDiagram
    CUSTOMER ||--o{ ORDER : places
    ORDER ||--|{ LINE-ITEM : contains
    PRODUCT ||--o{ LINE-ITEM : "included in"
    CUSTOMER {
        string name
        string email
    }
    ORDER {
        int orderNumber
        date orderDate
    }
    LINE-ITEM {
        int quantity
        float price
    }
    PRODUCT {
        int productId
        string name
        float price
    }\`}
    />
  )
}

export default DiagramsEntityRelationShipDemo
`,
  "@/registry-components/examples/dialog-demo/dialog-bottom-demo": `import { Button } from "@/components/library/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/library/dialog"

const DialogBottomDemo = () => {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Bottom Dialog</Button>
      </DialogTrigger>
      <DialogContent position="bottom">
        <DialogHeader>
          <DialogTitle>Bottom Dialog</DialogTitle>
          <DialogDescription>
            This is an example of a dialog positioned at the bottom.
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  )
}

export default DialogBottomDemo
`,
  "@/registry-components/examples/dialog-demo/dialog-demo": `"use client"
import { useState } from "react"

import { Button } from "@/components/library/button"
import {
  Dialog,
  DialogAction,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/library/dialog"
import { Label } from "@/components/library/label"

export default function DialogDemo() {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="default">Open Dialog</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Account Settings</DialogTitle>
          <DialogDescription>
            Manage your account preferences and settings.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Email Notifications
            </label>
            <div className="flex items-center">
              <input
                type="checkbox"
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
              />
              <span className="ml-2 text-sm text-gray-600 dark:text-gray-400">
                Receive email updates
              </span>
            </div>
          </div>
          <div>
            <Label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Profile Visibility
            </Label>
            <select className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-lg ">
              <option>Public</option>
              <option>Private</option>
              <option>Friends Only</option>
            </select>
          </div>
        </div>
        <DialogFooter>
          <DialogAction onClick={() => setIsOpen(false)}>
            Save Changes
          </DialogAction>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
`,
  "@/registry-components/examples/dialog-demo/dialog-destructive-demo": `"use client"
import { AlertTriangle, Trash2 } from "lucide-react"
import { useState } from "react"
import { Button } from "@/components/library/button"
import {
  Dialog,
  DialogAction,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/library/dialog"

export default function DestructiveDialogDemo() {
  const [isDeleting, setIsDeleting] = useState(false)
  const [itemDeleted, setItemDeleted] = useState(false)

  const handleDelete = () => {
    setIsDeleting(true)
    setTimeout(() => {
      setIsDeleting(false)
      setItemDeleted(true)
    }, 1500)
  }

  return (
    <div>
      {itemDeleted ? (
        <div className="bg-green-50 border border-green-200 p-4 rounded-lg text-center">
          <p className="text-green-700 font-medium">
            Item successfully deleted
          </p>
        </div>
      ) : (
        <Dialog>
          <DialogTrigger asChild>
            <Button variant="destructive">
              <Trash2 className="mr-1.5" /> Delete Project
            </Button>
          </DialogTrigger>
          <DialogContent appearance="destructive">
            <DialogHeader>
              <DialogTitle className="text-red-600 dark:text-red-400">
                Delete Permanent Project
              </DialogTitle>
              <DialogDescription className="text-red-800 dark:text-red-200">
                This will permanently delete the project "Marketing Campaign
                2024" and all associated data. This action cannot be undone.
              </DialogDescription>
            </DialogHeader>
            <div className="bg-red-50 dark:bg-red-950/50 p-4 rounded-lg mb-4">
              <div className="flex items-center">
                <AlertTriangle className="text-red-500 mr-3 flex-shrink-0" />
                <p className="text-red-700 dark:text-red-200 text-sm">
                  Warning: Deleting this project will remove all tasks,
                  documents, and analytics permanently.
                </p>
              </div>
            </div>
            <DialogFooter>
              <DialogAction
                variant="destructive"
                disabled={isDeleting}
                onClick={handleDelete}
                className="w-full"
              >
                {isDeleting ? "Deleting..." : "Permanently Delete Project"}
              </DialogAction>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </div>
  )
}
`,
  "@/registry-components/examples/dialog-demo/dialog-top-demo": `import { Button } from "@/components/library/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/library/dialog"

const DialogBottomDemo = () => {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Top Dialog</Button>
      </DialogTrigger>
      <DialogContent position="top">
        <DialogHeader>
          <DialogTitle>Top Dialog</DialogTitle>
          <DialogDescription>
            This is an example of a dialog positioned at the top.
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  )
}

export default DialogBottomDemo
`,
  "@/registry-components/examples/drawer-demo/drawer-demo": `"use client"

import { Button } from "@/components/library/button"
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/library/drawer"

export default function DrawerDemo() {
  return (
    <div>
      <Drawer>
        <DrawerTrigger asChild>
          <Button variant={"outline"}>Open Drawer</Button>
        </DrawerTrigger>
        <DrawerContent>
          <div className="mx-auto rounded-2xl max-w-md">
            <DrawerHeader>
              <DrawerTitle>Edit Profile</DrawerTitle>
              <DrawerDescription>
                Make changes to your profile here.
              </DrawerDescription>
            </DrawerHeader>
            <div className="p-4">
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <label htmlFor="name" className="text-sm font-medium">
                    Name
                  </label>
                  <input
                    id="name"
                    placeholder="Enter your name"
                    className="w-full rounded-md border p-2"
                  />
                </div>
                <div className="grid gap-2">
                  <label htmlFor="email" className="text-sm font-medium">
                    Email
                  </label>
                  <input
                    id="email"
                    type="email"
                    placeholder="Enter your email"
                    className="w-full rounded-md border p-2"
                  />
                </div>
              </div>
            </div>
            <DrawerFooter className="flex-row justify-end space-x-2">
              <DrawerClose asChild>
                <Button variant="ghost">Cancel</Button>
              </DrawerClose>
              <Button>Save Changes</Button>
            </DrawerFooter>
          </div>
        </DrawerContent>
      </Drawer>
    </div>
  )
}
`,
  "@/registry-components/examples/drawer-demo/drawer-nested-demo": `import { Button } from "@/components/library/button"
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/library/drawer"

const NestedDrawerDemo = () => {
  return (
    <Drawer>
      <DrawerTrigger asChild>
        <Button variant="outline">Open Nested Drawer</Button>
      </DrawerTrigger>
      <DrawerContent>
        <div className="max-w-sm w-full mx-auto">
          <DrawerHeader>
            <DrawerTitle>First Level Drawer</DrawerTitle>
            <DrawerDescription>
              You can open another drawer from here.
            </DrawerDescription>
          </DrawerHeader>
          <div className="flex justify-center  p-4">
            <Drawer>
              <DrawerTrigger asChild>
                <Button>Open Second Drawer</Button>
              </DrawerTrigger>
              <DrawerContent>
                <div className="max-w-sm w-full mx-auto">
                  <DrawerHeader>
                    <DrawerTitle>Second Level Drawer</DrawerTitle>
                    <DrawerDescription>
                      This is a nested drawer.
                    </DrawerDescription>
                  </DrawerHeader>
                  <div className="p-4">
                    <p>
                      You can have multiple levels of drawers for complex UIs.
                    </p>
                  </div>
                  <DrawerFooter>
                    <DrawerClose asChild>
                      <Button variant="outline">Close</Button>
                    </DrawerClose>
                  </DrawerFooter>
                </div>
              </DrawerContent>
            </Drawer>
          </div>
          <DrawerFooter>
            <DrawerClose asChild>
              <Button variant="outline">Close</Button>
            </DrawerClose>
          </DrawerFooter>
        </div>
      </DrawerContent>
    </Drawer>
  )
}

export default NestedDrawerDemo
`,
  "@/registry-components/examples/dropdown-menu-demo/dropdown-menu-checkbox-demo": `"use client"

import { useState } from "react"

import { Button } from "@/components/library/button"
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/library/dropdown-menu"

const DropDownCheckboxDemo = () => {
  const [showIcons, setShowIcons] = useState(false)
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">View Options</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56">
        <DropdownMenuLabel>Preferences</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuCheckboxItem
          checked={showIcons}
          onCheckedChange={setShowIcons}
        >
          Show Icons
        </DropdownMenuCheckboxItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export default DropDownCheckboxDemo
`,
  "@/registry-components/examples/dropdown-menu-demo/dropdown-menu-demo": `import { Download, Edit, Share } from "lucide-react"

import { Button } from "@/components/library/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/library/dropdown-menu"

const DropdownMenuDemo = () => {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">Open Menu</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56">
        <DropdownMenuLabel>My Account</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem>
          <Edit className="mr-2 h-4 w-4" />
          <span>Edit Profile</span>
        </DropdownMenuItem>
        <DropdownMenuItem>
          <Download className="mr-2 h-4 w-4" />
          <span>Download</span>
        </DropdownMenuItem>
        <DropdownMenuItem disabled>
          <Share className="mr-2 h-4 w-4" />
          <span>Share (Disabled)</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export default DropdownMenuDemo
`,
  "@/registry-components/examples/dropdown-menu-demo/dropdown-menu-nested-demo": `import { Camera, Trash2 } from "lucide-react"

import { Button } from "@/components/library/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "@/components/library/dropdown-menu"

const DropDownMenuNestedDemo = () => {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">Actions</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56">
        <DropdownMenuGroup>
          <DropdownMenuItem>
            <Camera className="mr-2 h-4 w-4" />
            <span>Camera</span>
          </DropdownMenuItem>
          <DropdownMenuSub>
            <DropdownMenuSubTrigger>
              <Trash2 className="mr-2 h-4 w-4" />
              <span>Delete</span>
            </DropdownMenuSubTrigger>
            <DropdownMenuSubContent>
              <DropdownMenuItem>Delete Item</DropdownMenuItem>
              <DropdownMenuItem>Delete All</DropdownMenuItem>
            </DropdownMenuSubContent>
          </DropdownMenuSub>
        </DropdownMenuGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export default DropDownMenuNestedDemo
`,
  "@/registry-components/examples/dropdown-menu-demo/dropdown-menu-radio-demo": `"use client"

import { useState } from "react"

import { Button } from "@/components/library/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuLabel,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/library/dropdown-menu"

const DropdownRadioDemo = () => {
  const [selectedPlan, setSelectedPlan] = useState("basic")
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline">Select Plan</Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56">
        <DropdownMenuLabel>Subscription Plan</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuRadioGroup
          value={selectedPlan}
          onValueChange={setSelectedPlan}
        >
          <DropdownMenuRadioItem value="basic">Basic</DropdownMenuRadioItem>
          <DropdownMenuRadioItem value="pro">Pro</DropdownMenuRadioItem>
          <DropdownMenuRadioItem value="enterprise">
            Enterprise
          </DropdownMenuRadioItem>
        </DropdownMenuRadioGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

export default DropdownRadioDemo
`,
  "@/registry-components/examples/folder-tree-demo": `"use client"

import { FolderTreeComponent } from "@/components/library/FolderTreeComponent"

type FileItem = {
  id: string
  name: string
  type: "file" | "folder"
  path?: string
  items?: FileItem[]
}

const fileStructure: FileItem[] = [
  {
    id: "app",
    name: "app",
    type: "folder",
    items: [
      {
        id: "layout",
        name: "layout.js",
        type: "file",
      },
      {
        id: "marketing",
        name: "(marketing)",
        type: "folder",
        items: [
          {
            id: "about",
            name: "about",
            type: "folder",
            path: "/about",
            items: [
              {
                id: "about-page",
                name: "page.js",
                type: "file",
              },
            ],
          },
          {
            id: "blog",
            name: "blog",
            type: "folder",
            path: "/blog",
            items: [
              {
                id: "blog-page",
                name: "page.js",
                type: "file",
              },
            ],
          },
        ],
      },
      {
        id: "shop",
        name: "(shop)",
        type: "folder",
        items: [
          {
            id: "account",
            name: "account",
            type: "folder",
            path: "/account",
            items: [
              {
                id: "account-page",
                name: "page.js",
                type: "file",
              },
            ],
          },
        ],
      },
    ],
  },
]

export default function FolderTreeDemo() {
  return (
    <div className="flex items-center justify-center ">
      <FolderTreeComponent items={fileStructure} />
    </div>
  )
}
`,
  "@/registry-components/examples/input-demo/input-button-demo": `import { Button } from "@/components/library/button"
import { Input } from "@/components/library/input"

export default function InputWithButtonDemo() {
  return (
    <div className="flex w-full max-w-sm items-center space-x-2">
      <Input type="email" placeholder="Email" />
      <Button type="submit" size={"sm"}>
        Subscribe
      </Button>
    </div>
  )
}
`,
  "@/registry-components/examples/input-demo/input-demo": `import { Input } from "@/components/library/input"

const InputDemo = () => {
  return <Input className="w-56" type="email" placeholder="Email" />
}

export default InputDemo
`,
  "@/registry-components/examples/input-demo/input-disabled-demo": `import { Input } from "@/components/library/input"

export default function InputDisabledDemo() {
  return <Input disabled type="email" placeholder="Email" />
}
`,
  "@/registry-components/examples/input-demo/input-file-demo": `import { Input } from "@/components/library/input"
import { Label } from "@/components/library/label"

export default function InputFileDemo() {
  return (
    <div className="grid w-full max-w-sm items-center gap-1.5">
      <Label htmlFor="picture">Picture</Label>
      <Input id="picture" type="file" />
    </div>
  )
}
`,
  "@/registry-components/examples/input-demo/input-label-demo": `import { Input } from "@/components/library/input"
import { Label } from "@/components/library/label"

export default function InputWithLabel() {
  return (
    <div className="grid w-full max-w-sm items-center gap-1.5">
      <Label htmlFor="email">Email</Label>
      <Input type="email" id="email" placeholder="Email" />
    </div>
  )
}
`,
  "@/registry-components/examples/label-demo": `import { Checkbox } from "@/components/library/checkbox"
import { Label } from "@/components/library/label"

const LabelDemo = () => {
  return (
    <div className="flex items-center space-x-2">
      <Checkbox id="terms" />
      <Label
        htmlFor="terms"
        className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
      >
        Accept terms and conditions
      </Label>
    </div>
  )
}

export default LabelDemo
`,
  "@/registry-components/examples/note-demo/note-closable-demo": `import React from "react"

import { Note } from "@/components/library/note"

const NoteClosableDemo = () => {
  return (
    <Note variant="info" closable>
      **Turbopack** is a high-performance bundler and dev server for Next.js.
      Enabling this option ensures faster builds and an improved development
      experience.
    </Note>
  )
}

export default NoteClosableDemo
`,
  "@/registry-components/examples/note-demo/note-demo": `import { Note } from "@/components/library/note"

const NoteDemo = () => {
  return <Note variant="info">This is an informational note.</Note>
}

export default NoteDemo
`,
  "@/registry-components/examples/note-demo/note-error-demo": `import { Note } from "@/components/library/note"

const NoteErrorDemo = () => {
  return <Note variant="error">An error has occurred. Please try again.</Note>
}

export default NoteErrorDemo
`,
  "@/registry-components/examples/note-demo/note-success-demo": `import { Note } from "@/components/library/note"

const NoteSuccessDemo = () => {
  return <Note variant="success">Operation completed successfully!</Note>
}

export default NoteSuccessDemo
`,
  "@/registry-components/examples/note-demo/note-warning-demo": `import { Note } from "@/components/library/note"

const NoteWarningDemo = () => {
  return <Note variant="warning">Be careful with this action!</Note>
}

export default NoteWarningDemo
`,
  "@/registry-components/examples/popover-demo": `import { Button } from "@/components/library/button"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/library/popover"

export default function PopoverDemo() {
  return (
    <div className="flex justify-center">
      <Popover>
        <PopoverTrigger asChild>
          <Button variant="outline">Click for Information</Button>
        </PopoverTrigger>
        <PopoverContent>
          <div className="space-y-2">
            <h3 className="font-medium">What is a Popover?</h3>
            <p className="text-sm text-gray-500">
              A popover is a floating card that appears when a user interacts
              with a trigger element. It's commonly used for additional
              information or controls.
            </p>
          </div>
        </PopoverContent>
      </Popover>
    </div>
  )
}
`,
  "@/registry-components/examples/product-card-demo": `"use client"

import { useState } from "react"
import { Truck } from "lucide-react"

import { cn } from "@/lib/utils"
import { Badge } from "@/components/library/badge"

export default function ProductCardDemo() {
  const [isDetailsClicked, setIsDetailsClicked] = useState(false)
  return (
    <div className="select-none max-w-[300px] relative">
      <div className="absolute top-[3%] -left-[3%] z-10 px-[5px] py-[7px] flex items-center justify-center gap-2 text-background text-xs rounded-tl-[0] rounded-br-[5px] rounded-tr-[5px] rounded-bl-[0] bg-[#676769] dark:bg-[#dad4d4]">
        <Truck className="w-4 h-4" />
        Fast shipping
      </div>
      <div className="absolute right-[0px] z-10  flex items-center justify-center text-background text-xs">
        <Badge className="rounded-none text-sm" variant={"destructive"}>
          20%
        </Badge>
      </div>
      <div className="p-0">
        <div className="relative">
          <img
            src="/JY-BO-001-650MM-8W (1).png"
            alt="LED Chandelier"
            className="object-contain"
          />
        </div>
        <div className="space-y-1">
          <p className="text-[19px] mt-[10px] font-medium">PRODUCT-MC6015-H3</p>
          <h3 className=" leading-tight text-zinc-500">
            Aluminum Shade + Glass LED Chandelier With E27 Base & 36W
          </h3>
          <div className="flex items-baseline gap-2">
            <span className="text-lg font-bold text-red-500">EGP 2576.00</span>
            <span className="text-sm text-zinc-400 line-through">
              EGP 3219.00
            </span>
          </div>
        </div>
      </div>
      <div className="flex justify-between gap-2 mt-[10px]">
        <button
          className={cn("flex-1 border border-black py-2 px-2 rounded-md", {
            "bg-gray-100": isDetailsClicked,
          })}
          onClick={() => setIsDetailsClicked(true)}
        >
          More details
        </button>
        <button className="shrink-0 bg-black rounded-md py-1 px-2 ">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 576 512"
            width={20}
            height={20}
            fill="white"
          >
            <path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z" />
          </svg>
        </button>
      </div>
    </div>
  )
}
`,
  "@/registry-components/examples/scroll-area-demo/scroll-area-demo": `import { ScrollArea } from "@/components/library/scroll-area";

export default function ScrollAreaDemo() {
  return (
    <div className="mt-12 space-y-3">
      <div className="border rounded-lg border-gray-200 dark:border-gray-800 h-96 flex flex-col">
        <div className="p-4 border-b flex items-center space-x-2">
          <div className="w-8 h-8 rounded-full bg-blue-100 flex items-center justify-center text-blue-600 font-medium">
            UI
          </div>
          <div>
            <h3 className="font-medium">UI Library Discussion</h3>
            <p className="text-xs text-gray-500">3 participants</p>
          </div>
        </div>
        <div className="flex-1 flex flex-col" >
          <ScrollArea className="h-72">
            <div
              aria-hidden="true"
              className="absolute z-10 inset-x-0 bottom-0 h-12 bg-gradient-to-t from-white to-transparent dark:from-[#252525] dark:to-transparent pointer-events-none"
            />
            <div className="p-4 space-y-6">
              {[
                {
                  user: "Alex",
                  message: "Has anyone used the new ScrollArea component?",
                  time: "10:15 AM",
                  isCurrentUser: false,
                },
                {
                  user: "Taylor",
                  message:
                    "Yes, I've been using it for a dashboard project. It works great with complex layouts.",
                  time: "10:17 AM",
                  isCurrentUser: false,
                },
                {
                  user: "You",
                  message:
                    "I just integrated it into our design system. The auto-hiding scrollbar is a nice touch!",
                  time: "10:20 AM",
                  isCurrentUser: true,
                },
                {
                  user: "Alex",
                  message: "Can it handle horizontal scrolling as well?",
                  time: "10:22 AM",
                  isCurrentUser: false,
                },
                {
                  user: "You",
                  message:
                    "Yes, it supports both vertical and horizontal scrolling out of the box. You can also customize the scrollbar's appearance and behavior.",
                  time: "10:25 AM",
                  isCurrentUser: true,
                },
                {
                  user: "Taylor",
                  message:
                    "I found the alwaysShowScrollbar prop useful for touch devices where users might not know content is scrollable otherwise.",
                  time: "10:27 AM",
                  isCurrentUser: false,
                },
                {
                  user: "Alex",
                  message: "Does it handle window resize events properly?",
                  time: "10:30 AM",
                  isCurrentUser: false,
                },
                {
                  user: "You",
                  message:
                    "Yes, it updates appropriately on window resize. The component also manages scroll position effectively when content changes.",
                  time: "10:32 AM",
                  isCurrentUser: true,
                },
                {
                  user: "Taylor",
                  message:
                    "The fade-in/fade-out animations are smooth. I like how it doesn't distract from the content.",
                  time: "10:35 AM",
                  isCurrentUser: false,
                },
                {
                  user: "Alex",
                  message: "Any performance issues with larger content?",
                  time: "10:37 AM",
                  isCurrentUser: false,
                },
                {
                  user: "You",
                  message:
                    "It performs well even with very long content. It's built on Radix UI primitives, which are optimized for performance.",
                  time: "10:40 AM",
                  isCurrentUser: true,
                },
              ].map((message, index) => (
                <div
                  key={index}
                  className={\`flex \${message.isCurrentUser ? "justify-end" : "justify-start"}\`}
                >
                  <div
                    className={\`max-w-[70%] rounded-lg p-3 \${message.isCurrentUser
                        ? "bg-blue-500 text-white"
                        : "bg-gray-100 dark:bg-gray-800"
                      }\`}
                  >
                    {!message.isCurrentUser && (
                      <p className="font-medium text-sm mb-1">{message.user}</p>
                    )}
                    <p className="text-sm">{message.message}</p>
                    <p
                      className={\`text-xs mt-1 \${message.isCurrentUser
                          ? "text-blue-100"
                          : "text-gray-500"
                        }\`}
                    >
                      {message.time}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>
        </div>
        <div className="p-4 border-t">
          <div className="flex space-x-2">
            <input
              type="text"
              placeholder="Type a message..."
              className="flex-1 rounded-lg border border-gray-300 dark:border-gray-700 p-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-800"
            />
            <button className="bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium">
              Send
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}`,
  "@/registry-components/examples/scroll-area-demo/scroll-area-horizontal-demo": `import { ScrollArea, ScrollBar } from "@/components/library/scroll-area"

const HorizontalScrollDemo = () => {
  return (
    <div className="w-full max-w-3xl mx-auto p-6">
      <ScrollArea className="h-32 w-full rounded-md border">
        <div className="flex gap-4 p-4">
          {Array.from({ length: 20 }).map((_, i) => (
            <div
              key={i}
              className="flex-shrink-0 w-40 h-20 rounded-md bg-gray-100 flex items-center justify-center"
            >
              <span className="text-gray-500">Item {i + 1}</span>
            </div>
          ))}
        </div>
        <ScrollBar orientation="horizontal" />
      </ScrollArea>
    </div>
  )
}

export default HorizontalScrollDemo
`,
  "@/registry-components/examples/separator-demo/separator-demo": `"use client"

import { Separator } from "@/components/library/separator"

const SeparatorDemo = () => {
  return (
    <div className="p-4 rounded-lg">
      <div className="p-4">Content Above</div>
      <Separator weight="regular" />
      <div className="p-4">Content Below</div>
    </div>
  )
}

export default SeparatorDemo
`,
  "@/registry-components/examples/separator-demo/separator-horizontal-demo": `import React from "react"

import { Separator } from "@/components/library/separator"

const SeparatorHorizontalDemo = () => {
  return (
    <div className="p-4 rounded-lg">
      <div className="p-4">Content Above</div>
      <Separator weight="regular" />
      <div className="p-4">Content Below</div>
    </div>
  )
}

export default SeparatorHorizontalDemo
`,
  "@/registry-components/examples/separator-demo/separator-light-demo": `import { Separator } from "@/components/library/separator"

const SeparatorLightDemo = () => {
  return (
    <div className="p-4 rounded-lg ">
      <div className="p-4">Content Above</div>
      <Separator weight="light" />
      <div className="p-4">Content Below</div>
    </div>
  )
}

export default SeparatorLightDemo
`,
  "@/registry-components/examples/separator-demo/separator-regular-demo": `import { Separator } from "@/components/library/separator"

const SeparatorRegularDemo = () => {
  return (
    <div className="p-4 rounded-lg ">
      <div className="p-4">Content Above</div>
      <Separator weight="regular" />
      <div className="p-4">Content Below</div>
    </div>
  )
}

export default SeparatorRegularDemo
`,
  "@/registry-components/examples/separator-demo/separator-ultralight-demo": `import React from "react"

import { Separator } from "@/components/library/separator"

const SeparatorUltralightDemo = () => {
  return (
    <div className="p-4 rounded-lg ">
      <div className="p-4">Content Above</div>
      <Separator weight="ultralight" />
      <div className="p-4">Content Below</div>
    </div>
  )
}

export default SeparatorUltralightDemo
`,
  "@/registry-components/examples/sheet-demo/sheet-bottom-demo": `import { Heart, ShoppingCart, User } from "lucide-react"

import { Button } from "@/components/library/button"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/library/sheet"

const SheetBottomDemo = () => {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          Show Actions
        </Button>
      </SheetTrigger>
      <SheetContent side="bottom" className="h-64">
        <div className="max-w-md mx-auto">
          <SheetHeader>
            <SheetTitle>Actions</SheetTitle>
            <SheetDescription>Choose an action to perform</SheetDescription>
          </SheetHeader>
          <div className="py-4">
            <div className="grid grid-cols-3 gap-4">
              <Button
                variant="outline"
                className="h-24 flex flex-col items-center justify-center gap-2"
              >
                <User size={24} />
                <span>Profile</span>
              </Button>
              <Button
                variant="outline"
                className="h-24 flex flex-col items-center justify-center gap-2"
              >
                <ShoppingCart size={24} />
                <span>Cart</span>
              </Button>
              <Button
                variant="outline"
                className="h-24 flex flex-col items-center justify-center gap-2"
              >
                <Heart size={24} />
                <span>Favorites</span>
              </Button>
            </div>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  )
}

export default SheetBottomDemo
`,
  "@/registry-components/examples/sheet-demo/sheet-demo": `import { Settings } from "lucide-react"

import { Button } from "@/components/library/button"
import { Checkbox } from "@/components/library/checkbox"
import { Label } from "@/components/library/label"
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/library/sheet"

const SheetDemo = () => {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          <Settings size={16} />
          Open Settings
        </Button>
      </SheetTrigger>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>Settings</SheetTitle>
          <SheetDescription>
            Configure your application preferences here
          </SheetDescription>
        </SheetHeader>
        <div className="py-6">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Label
                htmlFor="dark-mode"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Dark Mode
              </Label>
              <Checkbox id="dark-mood" />
            </div>
            <div className="flex items-center justify-between">
              <Label
                htmlFor="notification"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Notification
              </Label>
              <Checkbox id="notification" />
            </div>
            <div className="flex items-center justify-between">
              <Label
                htmlFor="email-updates"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Email Updates
              </Label>
              <Checkbox id="email-updates" />
            </div>
          </div>
        </div>
        <SheetFooter>
          <SheetClose asChild>
            <Button>Save Changes</Button>
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  )
}

export default SheetDemo
`,
  "@/registry-components/examples/sheet-demo/sheet-left-demo": `import { Link } from "@/i18n/routing"
import { Heart, Menu, Settings, ShoppingCart, User } from "lucide-react"

import { Button } from "@/components/library/button"
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/library/sheet"

const SheetLeftDemo = () => {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          <Menu size={16} />
          Open Menu
        </Button>
      </SheetTrigger>
      <SheetContent side="left">
        <SheetHeader>
          <SheetTitle>Navigation</SheetTitle>
        </SheetHeader>
        <nav className="py-6">
          <ul className="space-y-4">
            <li>
              <Link
                href="#"
                className="flex items-center gap-3 p-2 hover:bg-slate-100 rounded"
              >
                <User size={18} />
                <span>Profile</span>
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="flex items-center gap-3 p-2 hover:bg-slate-100 rounded"
              >
                <ShoppingCart size={18} />
                <span>Orders</span>
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="flex items-center gap-3 p-2 hover:bg-slate-100 rounded"
              >
                <Heart size={18} />
                <span>Wishlist</span>
              </Link>
            </li>
            <li>
              <Link
                href="#"
                className="flex items-center gap-3 p-2 hover:bg-slate-100 rounded"
              >
                <Settings size={18} />
                <span>Settings</span>
              </Link>
            </li>
          </ul>
        </nav>
      </SheetContent>
    </Sheet>
  )
}

export default SheetLeftDemo
`,
  "@/registry-components/examples/sheet-demo/sheet-right-demo": `import { Settings } from "lucide-react"

import { Button } from "@/components/library/button"
import { Checkbox } from "@/components/library/checkbox"
import { Label } from "@/components/library/label"
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/library/sheet"

const SheetRightBottom = () => {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          <Settings size={16} />
          Open Settings
        </Button>
      </SheetTrigger>
      <SheetContent side="right">
        <SheetHeader>
          <SheetTitle>Settings</SheetTitle>
          <SheetDescription>
            Configure your application preferences here
          </SheetDescription>
        </SheetHeader>
        <div className="py-6">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <Label
                htmlFor="dark-mode"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Dark Mode
              </Label>
              <Checkbox id="dark-mood" />
            </div>
            <div className="flex items-center justify-between">
              <Label
                htmlFor="notification"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Notification
              </Label>
              <Checkbox id="notification" />
            </div>
            <div className="flex items-center justify-between">
              <Label
                htmlFor="email-updates"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Email Updates
              </Label>
              <Checkbox id="email-updates" />
            </div>
          </div>
        </div>
        <SheetFooter>
          <SheetClose asChild>
            <Button>Save Changes</Button>
          </SheetClose>
        </SheetFooter>
      </SheetContent>
    </Sheet>
  )
}

export default SheetRightBottom
`,
  "@/registry-components/examples/sheet-demo/sheet-top-demo": `import { Button } from "@/components/library/button"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/library/sheet"

const SheetTopDemo = () => {
  return (
    <Sheet>
      <SheetTrigger asChild>
        <Button variant="outline" className="flex items-center gap-2">
          Open Notifications
        </Button>
      </SheetTrigger>
      <SheetContent side="top" className="h-64">
        <div className="max-w-md mx-auto">
          <SheetHeader>
            <SheetTitle>Notifications</SheetTitle>
            <SheetDescription>Your recent notifications</SheetDescription>
          </SheetHeader>
          <div className="py-4">
            <div className="space-y-3">
              <div className="p-3 bg-slate-50 rounded-2xl border border-border">
                <p className="text-sm font-medium">New message from Alice</p>
                <p className="text-xs text-gray-500">2 minutes ago</p>
              </div>
              <div className="p-3 bg-slate-50 rounded-2xl border border-border">
                <p className="text-sm font-medium">Order #1234 has shipped</p>
                <p className="text-xs text-gray-500">1 hour ago</p>
              </div>
            </div>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  )
}

export default SheetTopDemo
`,
  "@/registry-components/examples/sonner-demo/sonner-demo": `import { toast } from "sonner"

import { Button } from "@/components/library/button"

const SonnerDemo = () => {
  return (
    <Button
      variant="outline"
      onClick={() =>
        toast("Event has been created", {
          description: "Sunday, December 03, 2023 at 9:00 AM",
          action: {
            label: "Undo",
            onClick: () => console.log("Undo"),
          },
        })
      }
    >
      Show Toast
    </Button>
  )
}

export default SonnerDemo
`,
  "@/registry-components/examples/steps-demo": `import { Link } from "@/i18n/routing"

import { Step, StepItem } from "@/components/library/step"

const StepsDemo = () => {
  return (
    <Step>
      <StepItem title="Step one">
        Make sure you have Node.js installed on your machine.{" "}
        <Link href={"https://nodejs.org"} className="!underline">
          You can download it from here
        </Link>
        .
      </StepItem>
      <StepItem title="Step two">
        After cloning the repository, navigate to the project directory and
        install the necessary dependencies:
      </StepItem>
      <StepItem title="step three">Start the development server:</StepItem>
    </Step>
  )
}

export default StepsDemo
`,
  "@/registry-components/examples/tabs-demo/tabs-demo-line": `import { cn } from "@/lib/utils"
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/library/tabs"

const TabsLineDemo = ({ className }: { className: string }) => {
  return (
    <Tabs defaultValue="preview" className="mt-4 w-full">
      <TabsList className="inline-flex h-9 items-center text-muted-foreground w-full justify-start rounded-none border-b bg-transparent p-0 mb-2">
        <TabsTrigger value="preview" className="active:shadow-none text-base">
          tab one
        </TabsTrigger>
        <TabsTrigger value="code" className="active:shadow-none text-base">
          tab two
        </TabsTrigger>
      </TabsList>
      <div className="w-full">
        <TabsContent
          value="preview"
          className={cn("border rounded-md p-4", className)}
        >
          <div className="h-16 p-5 text-xl">Content One</div>
        </TabsContent>
        <TabsContent value="code" className="rounded-md border p-4">
          <div className="h-16 p-5 text-xl">Content two</div>
        </TabsContent>
      </div>
    </Tabs>
  )
}

export default TabsLineDemo
`,
  "@/registry-components/examples/tabs-demo/tabs-demo": `import {
  Tabs,
  TabsContainer,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs"

export default function TabsDemo() {
  return (
    <Tabs defaultValue="tab1" className="w-full max-w-md mx-auto">
      <TabsList className="inline-flex h-9 items-center text-muted-foreground max-w-fit justify-start rounded-none bg-transparent">
        <TabsContainer className="bg-muted rounded-[7px]">
          <TabsTrigger value="tab1" className="text-sm sm:px-3 px-1">
            Tab 1
          </TabsTrigger>
          <TabsTrigger value="tab2" className="text-sm sm:px-3 px-1">
            Tab 2
          </TabsTrigger>
          <TabsTrigger value="tab3" className="text-sm sm:px-3 px-1">
            Tab 3
          </TabsTrigger>
        </TabsContainer>
      </TabsList>
      <TabsContent value="tab1">
        <div className="p-4 bg-gray-100 rounded-md">Content for Tab 1</div>
      </TabsContent>
      <TabsContent value="tab2">
        <div className="p-4 bg-gray-100 rounded-md">Content for Tab 2</div>
      </TabsContent>
      <TabsContent value="tab3">
        <div className="p-4 bg-gray-100 rounded-md">Content for Tab 3</div>
      </TabsContent>
    </Tabs>
  )
}
`,
  "@/registry-components/examples/tooltip-demo/tooltip-bottom-demo": `import { Button } from "@/components/library/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/library/tooltip"

const TooltipDelayDemo = () => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline">Hover</Button>
        </TooltipTrigger>
        <TooltipContent side="bottom">
          <p>Bottom Tooltip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

export default TooltipDelayDemo
`,
  "@/registry-components/examples/tooltip-demo/tooltip-delay-demo": `import { Button } from "@/components/library/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/library/tooltip"

const TooltipDelayDemo = () => {
  return (
    <TooltipProvider delayDuration={500}>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline">Hover</Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>Delay Tooltip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

export default TooltipDelayDemo
`,
  "@/registry-components/examples/tooltip-demo/tooltip-demo": `import { Button } from "@/components/library/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/library/tooltip"

const TooltipDemo = () => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline">Hover</Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>Default Tooltip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

export default TooltipDemo
`,
  "@/registry-components/examples/tooltip-demo/tooltip-left-demo": `import { Button } from "@/components/library/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/library/tooltip"

const TooltipDelayDemo = () => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline">Hover</Button>
        </TooltipTrigger>
        <TooltipContent side="left">
          <p>Left Tooltip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

export default TooltipDelayDemo
`,
  "@/registry-components/examples/tooltip-demo/tooltip-right-demo": `import { Button } from "@/components/library/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/library/tooltip"

const TooltipDelayDemo = () => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline">Hover</Button>
        </TooltipTrigger>
        <TooltipContent side="right">
          <p>Right Tooltip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

export default TooltipDelayDemo
`,
  "@/registry-components/examples/tooltip-demo/tooltip-top-demo": `import { Button } from "@/components/library/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/library/tooltip"

const TooltipTopDemo = () => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="outline">Hover</Button>
        </TooltipTrigger>
        <TooltipContent side="top">
          <p>Top Tooltip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

export default TooltipTopDemo
`
};
