// This file was automatically generated by component-utils.mjs
  import { componentExamples } from "./component-examples"
  
  export const REGISTRY_COMPONENTS = {
    name: "alphabyte-labs",
    items: [...componentExamples.items],
  }
  